spring:
  application:
    name: MicrometerJmsStaticFactoryTracing

amqp-jms:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  tracing:
    propagation:
      type: ${TRACING_PROPAGATION_TYPE:B3}

logging:
  level:
    root: INFO
    org:
      springframework: ERROR
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level [${spring.application.name:}, traceId: %X{traceId}, spanId: %X{spanId}] --- %msg%n"



server:
  port: 8082