name: CI

on:
  push:
    branches: [ "dev","stg" ]
    tags: [ "v*" ]

  workflow_dispatch:

env:
  FILE_NAME: Changelog.MD

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      inside: inside_build

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: | 
          echo Hello, world! $FILE_NAME
          echo $inside
          echo $outside

      - name: Run a multi-line script
        run: |
          echo Hello, world! $FILE_NAME
          echo $inside
          echo $outside
        env: 
          outside: inside_step